services:
  mongodb:
    image: 'mongo:latest'
    environment:
#      - 'MONGO_INITDB_DATABASE=mongo_database'
      - 'MONGO_INITDB_ROOT_PASSWORD=mongo_password'
      - 'MONGO_INITDB_ROOT_USERNAME=mongo_user'
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres_database'
      - 'POSTGRES_PASSWORD=postgres_password'
      - 'POSTGRES_USER=postgres_user'
    ports:
      - '5432:5432'

volumes:
  mongodb_data:
    driver: local
