services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres_database'
      - 'POSTGRES_PASSWORD=postgres_password'
      - 'POSTGRES_USER=postgres_user'
    ports:
      - '5432:5432'
